// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

const TableNameDataAdminPermission = "data_admin_permission"

// DataAdminPermission mapped from table <data_admin_permission>
type DataAdminPermission struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"` // 主键id
	Name       string `gorm:"column:name;not null;comment:权限名称" json:"name"`                  // 权限名称
	PermSymbol string `gorm:"column:perm_symbol;not null;comment:权限标识" json:"perm_symbol"`    // 权限标识
	Sort       int32  `gorm:"column:sort;not null;comment:排序" json:"sort"`                    // 排序
	ParentID   int64  `gorm:"column:parent_id;not null;comment:父权限序号" json:"parent_id"`       // 父权限序号
	CreateTime int64  `gorm:"column:create_time;not null;comment:创建时间戳" json:"create_time"`   // 创建时间戳
	UpdateTime int64  `gorm:"column:update_time;not null;comment:更新时间戳" json:"update_time"`   // 更新时间戳
}

// TableName DataAdminPermission's table name
func (*DataAdminPermission) TableName() string {
	return TableNameDataAdminPermission
}
